---
- name: "Playing with Ansible and Git"
  hosts: localhost
  connection: local

  tasks:
    - name: Ensure work directory exists
      file:
        path: "{{ work_dir }}"
        state: directory

    - name: "Update repositories from templates"
      include: "update_repo.yaml"
      with_items: "{{ repositories }}"

    - name: "List directory"
      shell: tree
      register: dirtree

    - name: Show tree
      debug:
        msg: "{{ dirtree }}"
