---
- name: Synchronize operator template files with operator repositories
  hosts: localhost
  connection: local

  tasks:
    - name: Include data which repositories to check
      include_vars: ../repositories.yaml
      tags: local

    - name: Ensure work directory exists
      file:
        path: "{{ work_dir }}"
        state: directory

    - name: Configure git author mail
      command:
        argv: [git, config, --global, user.email, "{{ author_mail }}"]

    - name: Configure git author name
      command:
        argv: [git, config, --global, user.name, "{{ author_name }}"]

    - name: Login to github
      command:
        argv: [gh, auth, login, --with-token]
        stdin: "{{ gh_access_token }}"
      register: loginresult
      ignore_errors: true

    - name: Update repositories from templates
      include_tasks: "update_repo.yaml"
      with_items: "{{ repositories }}"
      loop_control:
        loop_var: operator
        index_var: operator_index
      tags: local
