---
- name: "Playing with Ansible and Git"
  hosts: localhost
  connection: local

  tasks:
    - name: current_working_directory
      shell: pwd
      register: current_working_directory

    - name: "Update repositories from templates"
      include: "update_repo.yaml"
      with_items: "{{ repositories }}"

    - name: "Show workdir"
      shell: cd .. && pwd
      register: workdir

    - name: Show workdir - debug
      debug:
        msg: "{{ workdir }}"

    - name: "List directory"
      shell: tree
      register: dirtree

    - name: Show tree
      debug:
        msg: "{{ dirtree }}"
