---
- name: Synchronize operator template files with operator repositories
  hosts: localhost
  connection: local

  tasks:
    - name: Include data which repositories to check
      include_vars: ../repositories.yaml
      tags: local

    - name: Ensure work directory exists
      file:
        path: "{{ work_dir }}"
        state: directory

    - name: Configure git author mail
      shell: git config --global user.email "{{ author_mail }}"

    - name: Configure git author name
      shell: git config --global user.name "{{ author_name }}"

    - name: Login to github
      shell: echo "{{ gh_access_token }}" | gh auth login --with-token
      register: loginresult
      ignore_errors: yes

    - name: Update repositories from templates
      include: "update_repo.yaml"
      with_items: "{{ repositories }}"
      loop_control:
        loop_var: operator