---
- name: "Playing with Ansible and Git"
  hosts: localhost
  connection: local

  tasks:
    - name: Include data which repositories to check
      include_vars: ../repositories.yaml

    - name: Show workdir
      debug:
        msg: "{{ work_dir }}"

    - name: Ensure work directory exists
      file:
        path: "{{ work_dir }}"
        state: directory

    - name: Configure git author mail
      shell: git config --global user.email "soenke.liebau@stackable.de"

    - name: Configure git author name
      shell: git config --global user.name "Sönke Liebau"

    - name: Login to github
      shell: echo "{{ gh_access_token }}" | gh auth login --with-token
      register: loginresult
      ignore_errors: yes

    - debug:
        msg: "{{ loginresult }}"

    - name: "Update repositories from templates"
      include: "update_repo.yaml"
      with_items: "{{ repositories }}"
      loop_control:
        loop_var: operator

    - name: "List directory"
      shell: tree {{ work_dir }}
      register: dirtree

    - name: Show tree
      debug:
        msg: "{{ dirtree }}"
