---
- name: Synchronize operator template files with operator repositories
  hosts: localhost
  connection: local

  tasks:
    - name: Include data which repositories to check
      include_vars: "{{ item }}"
      tags: local
      with_fileglob:
        - "../config/*.yaml"

    - name: Ensure work directory exists
      file:
        path: "{{ work_dir }}"
        state: directory

    - name: Login to github
      command:
        argv: [gh, auth, login, --with-token]
        stdin: "{{ gh_access_token }}"
      register: loginresult
      ignore_errors: true

    - name: Update repositories from templates
      include_tasks: "update_repo.yaml"
      with_items: "{{ repositories }}"
      loop_control:
        loop_var: operator
        index_var: operator_index
      tags: local
