- debug:
    msg: "{{ item }}"

- name: Login to github
  shell: echo "{{ gh_access_token }}" | gh auth login --with-token
  register: loginresult
  ignore_errors: yes

- debug:
      msg: "{{ loginresult }}"

- name: Clone {{ item.name }}
  shell: gh repo clone {{ item.url }}

