- debug:
    msg: "{{ item }}"

- shell: gh auth login --with-token {{ gh_access_token }}
  register: loginresult
  ignore_errors: yes

- debug:
      msg: "{{ loginresult.stdout }}"

- shell: gh repo clone {{ item.url }}

