- debug:
    msg: "{{ item }}"

- name: Login to github
  shell: echo "{{ gh_access_token }}" | gh auth login --with-token
  register: loginresult
  ignore_errors: yes

- debug:
      msg: "{{ loginresult }}"

- name: Clone
  shell: gh repo clone {{ item.url }} {{ workdir.stdout}}/{{ item.name }}

- name: Create new branch
  shell:
    cmd: git checkout -b testbranch
    chdir: "{{ workdir.stdout}}/{{ item.name }}"

- name: git status
  shell: git status
  args:
    chdir: "{{ workdir.stdout}}/{{ item.name }}"
    register: status

- debug:
    msg: "{{ status }}"
