- debug:
    msg: "{{ operator }}"

- name: Login to github
  shell: echo "{{ gh_access_token }}" | gh auth login --with-token
  register: loginresult
  ignore_errors: yes

- debug:
      msg: "{{ loginresult }}"

- name: Clone
  shell: gh repo clone {{ operator.url }} "{{ work_dir }}/{{ operator.name }}"
  register: cloneresult

- debug:
    msg: "{{ cloneresult }}"

- name: Create new branch
  shell: git checkout -b testbranch
  args:
    chdir: "{{ work_dir }}/{{ operator.name }}"

- name: "Find j2 files"
  find:
    paths: "{{ template_dir }}/"
    patterns: "*.j2"
    file_type: file
    use_regex: no
    recurse: yes
  register: files_j2

- debug:
    msg: "{{ files_j2 }}"

- name: "Find normal files"
  find:
    paths: "{{ template_dir }}/"
    excludes: "*.j2"
    file_type: file
    use_regex: no
    recurse: yes
  register: files_normal

- debug:
    msg: "{{ files_normal }}"

- name: "Ensure directory exists"
  file:
    path: "{{ item.path | replace(template_dir, work_dir + '/' + operator.name) | dirname }}"
    state: directory
  with_items:
    - "{{ files_j2.files }}"
    - "{{ files_normal.files }}"

- name: "Copy templates files"
  template:
    src: "{{ item.path }}"
    mode: "preserve"
    dest: "{{ item.path | replace(template_dir, work_dir + '/' + operator.name) | regex_replace('.j2$', '') }}"
    variable_start_string: [[
    variable_end_string: ]]
  with_items: "{{ files_j2.files }}"

- name: "Copy normal files to temp directory"
  template:
    src: "{{ item.path }}"
    mode: "preserve"
    dest: "{{ item.path | replace(template_dir, work_dir + '/' + operator.name) }}"
  with_items: "{{ files_normal.files }}"

#
#- name: Commit changes
#  shell: git commit -m 'test'
#  args:
#    chdir: "{{ work_dir }}/{{ item.name }}"
#
- name: git status
  shell: git status
  args:
    chdir: "{{ work_dir }}/{{ operator.name }}"
  register: status

- debug:
    msg: "{{ status }}"
