- debug:
    msg: "{{ item }}"

- shell: echo "{{ gh_access_token }}" | gh auth login --with-token
  register: loginresult
  ignore_errors: yes

- debug:
      msg: "{{ loginresult }}"

- shell: gh repo clone {{ item.url }}

