---
extends: default

ignore:
  # yamllint can't parse these files as yaml because of j2 templating
  - template/.github/ISSUE_TEMPLATE/bug_report.yml.j2
  - template/deploy/helm/\[\[operator\]\]/Chart.yaml.j2
  - template/deploy/helm/**/templates

rules:
  line-length: disable
  truthy:
    check-keys: false
  comments:
    min-spaces-from-content: 1  # Needed due to https://github.com/adrienverge/yamllint/issues/443
  comments-indentation: disable # This is generally useless and interferes with commented example values
  braces:
    max-spaces-inside: 1
    max-spaces-inside-empty: 0

yaml-files:
  - '*.yaml'
  - '*.yml'
  - '.yamllint'
  - '*.yaml.j2'
  - '*.yml.j2'
