---
extends: default

ignore: |
  template/deploy/helm/**/templates

rules:
  line-length: disable
  truthy:
    check-keys: false
  comments:
    min-spaces-from-content: 1  # Needed due to https://github.com/adrienverge/yamllint/issues/443

yaml-files:
  - '*.yaml'
  - '*.yml'
  - '.yamllint'
  - '*.yaml.j2'
  - '*.yml.j2'