---
name: Generate Downstream PRs

on:
  workflow_dispatch:
    inputs:
      message:
        description: "Message to include in the generated commits:"
        required: true
        #  schedule:
        #    - cron: 5 4 * * * # run at 04:05 every morning

jobs:
  create-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Install Ansible
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
            sudo apt update &&  \
            sudo apt install -y software-properties-common && \
            sudo apt-add-repository ppa:ansible/ansible -y && \
            sudo apt install -y ansible

      - name: Install deps for operators
        run: |
          sudo apt-get install \
          protobuf-compiler \
          krb5-user \
          libclang-dev \
          libkrb5-dev \
          liblzma-dev \
          libssl-dev \
          pkg-config

      - name: Install jinja2
        run: pip install -r requirements.txt

      # Create commit message depending on whether this is run manually or due to a scheduled run
      - name: Set commit message for manual dispatch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "REASON=Manual run triggered by: ${{ github.event.sender.login }} with message [${{ github.event.inputs.message }}]" >> "$GITHUB_ENV"
      - name: Set commit message for schedule
        if: ${{ github.event_name == 'schedule' }}
        run: |
          echo "REASON=Daily run triggered" >> "$GITHUB_ENV"

      # Generate PRs
      - name: Run playbook
        run: |
          # Funnel via JSON to ensure that values are escaped properly
          echo '{}' | jq '{commit_hash: $ENV.GITHUB_SHA, reason: $ENV.REASON, base_dir: $pwd,  gh_access_token: $ENV.GH_ACCESS_TOKEN}' --arg pwd "$(pwd)" > vars.json
          ansible-playbook playbook/playbook.yaml --extra-vars "@vars.json"
        env:
          GH_ACCESS_TOKEN: ${{ secrets.gh_access_token }}
